# Generated by Django 3.1.3 on 2021-05-11 16:36

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_delete_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200, validators=[comment.models.comment_validator]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(validators=[comment.models.rate_validator]),
        ),
    ]
