# Generated by Django 3.1.3 on 2021-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
