# Generated by Django 3.1.3 on 2021-05-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210503_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
